{% set name = "genesis4" %}
{% set version = "4.6.8" %}

# ensure mpi is defined (needed for conda-smithy recipe-lint)
{% set mpi = mpi or 'mpich' %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/svenreiche/Genesis-1.3-Version4/archive/v{{ version }}.tar.gz
  sha256: 8cdca2cbd4966a131899dda6749edfd9cb5f9b562fa271b1358a1f7081c5e8d6

build:
  skip: true  # [win]
  number: 0

  # add build string so packages can depend on mpi variants explicitly:
  # `pkg * mpi_mpich_*` for mpich
  # `pkg * mpi_*` for any mpi

  {% set mpi_prefix = "mpi_" + mpi %}
  string: {{ mpi_prefix }}_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}

  run_exports:
    - {{ name }} * {{ mpi_prefix }}_*

requirements:
  build:
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
    - {{ compiler("cxx") }}
    - {{ mpi }}
    - cmake
    - make
    - pkg-config
  host:
    - {{ mpi }}
    - fftw * mpi_{{ mpi }}_*
    - hdf5 {{ hdf5 }} mpi_{{ mpi }}_*
  run:
    - {{ mpi }}

test:
  commands:
    - which genesis4

about:
  home: https://github.com/svenreiche/Genesis-1.3-Version4/
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: GENESIS 1.3 is a time-dependent three-dimensional FEL code.
  description: |
    GENESIS 1.3 version 4 simulates the interaction of electrons within the
    magnetic field of an undulator to produce coherent radiation, based on the
    Free-electron Laser process.
  doc_url: http://genesis.web.psi.ch/
  dev_url: https://github.com/svenreiche/Genesis-1.3-Version4/

extra:
  recipe-maintainers:
    - ken-lauer
    - ChristopherMayes
