# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

jobs:
- job: osx
  pool:
    vmImage: macOS-12
  strategy:
    matrix:
      osx_64_hdf51.10.6mpimpich:
        CONFIG: osx_64_hdf51.10.6mpimpich
        UPLOAD_PACKAGES: 'True'
      osx_64_hdf51.10.6mpiopenmpi:
        CONFIG: osx_64_hdf51.10.6mpiopenmpi
        UPLOAD_PACKAGES: 'True'
      osx_64_hdf51.12.0mpimpich:
        CONFIG: osx_64_hdf51.12.0mpimpich
        UPLOAD_PACKAGES: 'True'
      osx_64_hdf51.12.0mpiopenmpi:
        CONFIG: osx_64_hdf51.12.0mpiopenmpi
        UPLOAD_PACKAGES: 'True'
      osx_64_hdf51.12.1mpimpich:
        CONFIG: osx_64_hdf51.12.1mpimpich
        UPLOAD_PACKAGES: 'True'
      osx_64_hdf51.12.1mpiopenmpi:
        CONFIG: osx_64_hdf51.12.1mpiopenmpi
        UPLOAD_PACKAGES: 'True'
      osx_64_hdf51.12.2mpimpich:
        CONFIG: osx_64_hdf51.12.2mpimpich
        UPLOAD_PACKAGES: 'True'
      osx_64_hdf51.12.2mpiopenmpi:
        CONFIG: osx_64_hdf51.12.2mpiopenmpi
        UPLOAD_PACKAGES: 'True'
      osx_64_hdf51.14.1mpimpich:
        CONFIG: osx_64_hdf51.14.1mpimpich
        UPLOAD_PACKAGES: 'True'
      osx_64_hdf51.14.1mpiopenmpi:
        CONFIG: osx_64_hdf51.14.1mpiopenmpi
        UPLOAD_PACKAGES: 'True'
      osx_64_hdf51.14.2mpimpich:
        CONFIG: osx_64_hdf51.14.2mpimpich
        UPLOAD_PACKAGES: 'True'
      osx_64_hdf51.14.2mpiopenmpi:
        CONFIG: osx_64_hdf51.14.2mpiopenmpi
        UPLOAD_PACKAGES: 'True'
      osx_64_hdf51.14.3mpimpich:
        CONFIG: osx_64_hdf51.14.3mpimpich
        UPLOAD_PACKAGES: 'True'
      osx_64_hdf51.14.3mpiopenmpi:
        CONFIG: osx_64_hdf51.14.3mpiopenmpi
        UPLOAD_PACKAGES: 'True'
      osx_arm64_hdf51.10.6mpimpich:
        CONFIG: osx_arm64_hdf51.10.6mpimpich
        UPLOAD_PACKAGES: 'True'
      osx_arm64_hdf51.10.6mpiopenmpi:
        CONFIG: osx_arm64_hdf51.10.6mpiopenmpi
        UPLOAD_PACKAGES: 'True'
      osx_arm64_hdf51.12.0mpimpich:
        CONFIG: osx_arm64_hdf51.12.0mpimpich
        UPLOAD_PACKAGES: 'True'
      osx_arm64_hdf51.12.0mpiopenmpi:
        CONFIG: osx_arm64_hdf51.12.0mpiopenmpi
        UPLOAD_PACKAGES: 'True'
      osx_arm64_hdf51.12.1mpimpich:
        CONFIG: osx_arm64_hdf51.12.1mpimpich
        UPLOAD_PACKAGES: 'True'
      osx_arm64_hdf51.12.1mpiopenmpi:
        CONFIG: osx_arm64_hdf51.12.1mpiopenmpi
        UPLOAD_PACKAGES: 'True'
      osx_arm64_hdf51.12.2mpimpich:
        CONFIG: osx_arm64_hdf51.12.2mpimpich
        UPLOAD_PACKAGES: 'True'
      osx_arm64_hdf51.12.2mpiopenmpi:
        CONFIG: osx_arm64_hdf51.12.2mpiopenmpi
        UPLOAD_PACKAGES: 'True'
      osx_arm64_hdf51.14.1mpimpich:
        CONFIG: osx_arm64_hdf51.14.1mpimpich
        UPLOAD_PACKAGES: 'True'
      osx_arm64_hdf51.14.1mpiopenmpi:
        CONFIG: osx_arm64_hdf51.14.1mpiopenmpi
        UPLOAD_PACKAGES: 'True'
      osx_arm64_hdf51.14.2mpimpich:
        CONFIG: osx_arm64_hdf51.14.2mpimpich
        UPLOAD_PACKAGES: 'True'
      osx_arm64_hdf51.14.2mpiopenmpi:
        CONFIG: osx_arm64_hdf51.14.2mpiopenmpi
        UPLOAD_PACKAGES: 'True'
      osx_arm64_hdf51.14.3mpimpich:
        CONFIG: osx_arm64_hdf51.14.3mpimpich
        UPLOAD_PACKAGES: 'True'
      osx_arm64_hdf51.14.3mpiopenmpi:
        CONFIG: osx_arm64_hdf51.14.3mpiopenmpi
        UPLOAD_PACKAGES: 'True'
  timeoutInMinutes: 360
  variables: {}

  steps:
  # TODO: Fast finish on azure pipelines?
  - script: |
      export CI=azure
      export flow_run_id=azure_$(Build.BuildNumber).$(System.JobAttempt)
      export remote_url=$(Build.Repository.Uri)
      export sha=$(Build.SourceVersion)
      export OSX_FORCE_SDK_DOWNLOAD="1"
      export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
      export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
      if [[ "${BUILD_REASON:-}" == "PullRequest" ]]; then
        export IS_PR_BUILD="True"
      else
        export IS_PR_BUILD="False"
      fi
      ./.scripts/run_osx_build.sh
    displayName: Run OSX build
    env:
      BINSTAR_TOKEN: $(BINSTAR_TOKEN)
      FEEDSTOCK_TOKEN: $(FEEDSTOCK_TOKEN)
      STAGING_BINSTAR_TOKEN: $(STAGING_BINSTAR_TOKEN)